### ISSUE TITLE
dependency version requirements while packaging

### ISSUE THREAD

**Issue by fkooman** [yosymfony/Config-loader#4]
Hi,

I'm creating Fedora/CentOS/RHEL packages for `yosymfony/config-loader` and `yosymfony/toml`. I was wondering what the exact version requirements are for `yosymfony/config-loader`. The packages included in Fedora are for instance:

```
$ rpm -q php-symfony-config php-symfony-yaml
php-symfony-config-2.5.12-1.fc22.noarch
php-symfony-yaml-2.5.12-1.fc22.noarch
```

Are these versions sufficient for `yosymfony/config-loader`? The unit tests I run during building of the packages seem to run fine with those older versions, even on EPEL6, which contradicts with the `composer.json` version requirements...

Builds:
`php-yosymfony-config-loader`: https://copr.fedoraproject.org/coprs/fkooman/php-base/package/php-yosymfony-config-loader/
`php-yosymfony-toml`: https://copr.fedoraproject.org/coprs/fkooman/php-base/package/php-yosymfony-toml/

**Comment by yosymfony** [comment]
Hi. The PHP minimum version for `yosymfony/config-loader` is 5.3.3. Maybe in previous version it work fine but is not recommended. Further, although the minimum version is 5.3.3 I recommended to update to the latest version of PHP for security reasons. See http://blog.ircmaxell.com/2014/12/on-php-version-requirements.html

**Comment by fkooman** [comment]
Well, the point is that this is what is included in CentOS/RHEL 6. So while I understand it is (usually) best to use the latest stable version, that is not always an option :)
